### ISSUE TITLE
Where the License plugin expecting certificate?

### ISSUE THREAD

**Issue by tbobek-cen83785** [jbsouthe/AppDynamics-LicenseMonitoring-MAExtension#1]
Hi, what is the expected path to store the certificate?

[Agent-Monitor-Scheduler-2] 19 Oct 2023 14:08:39,976 ERROR Controller - Exception in attempting to get access token, Exception: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[Agent-Monitor-Scheduler-2] 19 Oct 2023 14:08:39,992 ERROR Controller - Exception in attempting to get controller data, Exception: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[Agent-Monitor-Scheduler-2] 19 Oct 2023 14:08:39,992 ERROR PeriodicTaskRunner - Error creating environment task

**Comment by jbsouthe** [comment]
This is a standard error suggesting that you do not have ssl client configured correctly, it does not appear to be an error in the extension
